In [1]:
import numpy as np


# Filter Array : 


In [2]:
a1  = np.array([11,24,7,76,23,54])

In [3]:
print(a1)

[11 24  7 76 23 54]


In [5]:
# Operators : >,< ,<=,>=,==,!=

# values > 30

#print(a1 > 30)

a1 > 30 

array([False, False, False,  True, False,  True])

In [6]:
new_data = a1 > 30 
print(new_data)

[False False False  True False  True]


In [9]:
new_a =np.where(a1 > 30)
# print(new_a)
new_a

(array([3, 5]),)

In [10]:
new_a[0]

array([3, 5])

In [17]:
my_tuple = 11,

In [18]:
print(type(my_tuple))

<class 'tuple'>


In [20]:
for index in new_a[0]:
    print(a1[index])

76
54


In [42]:
# Reshape : 

a2 = np.array([1,2,3,4,5,6,7,8,9,11,12,13])

In [22]:
a2 

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
print(np.reshape(a2,(3,3))) 
# print(np.reshape(a2,[3,3])) 

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [33]:
print(np.reshape(a2,(2,3)))  

[[1 2 3]
 [4 5 6]]


In [43]:
print(np.reshape(a2,(3,-1)))  


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 11 12 13]]


In [44]:
# +ve Negative

In [46]:
print(np.reshape(a2,(-1,3)))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]]


In [48]:
print(np.reshape(a2,(12,1)))


[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [11]
 [12]
 [13]]


In [49]:
print(np.reshape(a2,(6,-1)))


[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 11]
 [12 13]]


In [59]:
a3 = np.array([11,12,46,78,3,55,23])

In [51]:
a3

array([11, 12, 46, 78,  3, 55, 23])

In [52]:
print(a3 > 30)

[False False  True  True False  True False]


In [53]:
a3[a3 > 30]

array([46, 78, 55])

# Masking Array : 

In [ ]:
new_data_2 = a3 > 30

new_data_2

array([46, 78, 55])

In [60]:
a3 
a3[a3 > 30] = 0
a3 

array([11, 12,  0,  0,  3,  0, 23])

In [61]:
a1 = np.array([11,12,13,14])
a2 = np.array([1,2,3,4])

print(a1 + a2)


[12 14 16 18]


In [62]:
print(a1 + 10)

[21 22 23 24]


In [63]:
print(10 / a1)

[0.90909091 0.83333333 0.76923077 0.71428571]
