In [ ]:
print("Hello")

In [ ]:
print("NewLine")

In [ ]:
print("Third Line")

In [ ]:
import numpy as np

# Creating Array :

In [ ]:
l1 = [11,12,13,14,15]
l1 

In [ ]:
a1 = np.array(l1)
a1 

In [ ]:
a2 = np.zeros(5)
a2

In [ ]:
a3 = np.ones(10)
a3

In [ ]:
a4 = np.full(10,5)
a4

In [ ]:
v1 = np.random.rand()
v1

In [ ]:
v2 = np.random.randint(0,10)
v2

In [ ]:
a5 = np.arange(1,10)
a5

In [ ]:
a5 = np.arange(1,10,3)
a5

In [ ]:
a1 = np.array([11,12,13,14]) 
a1 

In [ ]:
a2 = np.array([
    [1,2,3],
    [3,4,5]
])
a2

In [ ]:
a3 = np.zeros(5)
a3

In [ ]:
a4 = np.zeros((5,3))
a4

In [ ]:
a5 = np.ones(3)
a5

In [ ]:
a6 = np.ones((2,2))
a6

In [ ]:
a7 = np.full(3,10)
a7

In [ ]:
a8 = np.full((3,3),2)

In [ ]:
a8

In [ ]:
a9 = np.full((3,3),(34,45,33))
a9 

In [ ]:
n = np.random.rand(2,3)
n 

In [ ]:
n2 = np.random.rand(5)
n2 

In [ ]:
n3 = np.random.randint(1,10)
n3 

In [ ]:
n4 = np.random.randint(1,10,4)
n4

In [ ]:
n5 = np.random.randint(1,10,(2,3))
n5 

In [ ]:
n6= np.arange(1,10)
n6 

In [ ]:
n7 = np.arange(1,20,3)
n7 

In [ ]:
n8 = np.eye(3,4)
n8 

# Indexing : 

In [5]:
import numpy as np

In [7]:
a1 = np.array([11,12,13,14,15])
a1 

array([11, 12, 13, 14, 15])

In [8]:
# index  : 
# always start with 0. (+ve)
# negative : -1

In [9]:
a1[0]

np.int64(11)

In [10]:
print(a1[0])

11


In [11]:
print(a1[3])

14


In [12]:
print(a1[-1])

15


In [13]:
a2 = np.array([[11,12,13],[14,15,16],[17,18,19]])
print(a2)

[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [14]:
print(a2[0][1])

12


In [15]:
print(a2[0][-1])


13


In [17]:
print(a2[-3][-2])

12


# Slicing :

In [18]:
a3 = np.array([11,2,3,4,3,7,88,4,11,33])
print(a3)

[11  2  3  4  3  7 88  4 11 33]


In [19]:
print(a3[1:])

[ 2  3  4  3  7 88  4 11 33]


In [20]:
print(a3[1:4])

[2 3 4]


In [21]:
print(a3[5:])

[ 7 88  4 11 33]


In [22]:
print(a3[5:8])

[ 7 88  4]


In [23]:
print(a3[1:8])

[ 2  3  4  3  7 88  4]


In [24]:
print(a3[1:8:1])

[ 2  3  4  3  7 88  4]


In [25]:
print(a3[1:8:2])

[2 4 7 4]


In [26]:
print(a3[1:8:5])

[ 2 88]


In [27]:
print(a3[1:8:-1])

[]


In [28]:
print(a3[1:8:-3])

[]


In [29]:
print(a3[-1:])

[33]


In [30]:
print(a3[-1:-5])

[]


In [31]:
print(a3[-5:-1])

[ 7 88  4 11]


In [34]:
print(a3[-5:-1 :2])

[7 4]
