In [1]:
import numpy as np

In [2]:
a1 = np.array([1,2,3,4])

In [3]:
a2 = np.array([5,6,7,8])

In [4]:
print(a1+a2)

[ 6  8 10 12]


In [5]:
print(a1-a2)
print(a2*a2)


[-4 -4 -4 -4]
[25 36 49 64]


In [6]:
print(a1/a2)

[0.2        0.33333333 0.42857143 0.5       ]


In [7]:
print(a2**a1)

[   5   36  343 4096]


In [21]:
a3 = np.array([4,16,25,36,-23,1])


In [10]:
print(np.sqrt(a3))

[2. 4. 5. 6.]


In [11]:
print(np.sqrt(100))

10.0


In [12]:
print(np.square(a3))

[  16  256  625 1296]


In [17]:
print(np.exp([10]))

[22026.46579481]


In [18]:
print(np.log(a3))

[1.38629436 2.77258872 3.21887582 3.58351894]


In [19]:
print(np.log10(a3))

[0.60205999 1.20411998 1.39794001 1.5563025 ]


In [22]:
print(np.abs(a3))

[ 4 16 25 36 23  1]


In [ ]:
a4  = np.array([np.pi,np.pi/2])
a4 
print(np.sin(a4))
print(np.cos(a4))
print(np.tan(a4))

array([3.14159265, 1.57079633])

In [29]:
print(np.sin(a4))
print(np.cos(a4))
print(np.tan(a4))

[1.2246468e-16 1.0000000e+00]
[-1.000000e+00  6.123234e-17]
[-1.22464680e-16  1.63312394e+16]


In [35]:
a5 = np.array([[1,2,3],[4,5,6]])


In [36]:
print(np.concatenate(a5))

[1 2 3 4 5 6]


In [37]:
a1 = np.array([1,2])
a2 = np.array([3,4])

In [38]:
print(np.hstack((a1,a2)))

[1 2 3 4]


In [39]:
print(np.vstack((a1,a2)))

[[1 2]
 [3 4]]
